### ISSUE TITLE
KML file support for Leaflet - License question

### ISSUE THREAD

**Issue by dawnbreak** [bobosch/ods_osm#10]
I have experimented with adding KML file support for leaflet library with a 3rd party plugin from https://github.com/shramov/leaflet-plugins.
Just wanted to prepare it for a pull request, but what license does ods_osm have? The 3rd party plugin has a non standard license, but permits redistribution. Any comments?

**Comment by bobosch** [comment]
Hi, currently I've not defined a license... what is your suggestion?

**Comment by dawnbreak** [comment]
OpenLayers is BSD-2, so quite liberal. But I just saw this "All rights reserved" with redistribution permitted from the 3rd party plugin is the same license as Leaflet itself. So adding this would make not much difference from the current state.
But I have no clue what is leagally correct for combining these different licenses into one plugin. GPL for sure is not possible, the other more liberal ones like BSD or MIT I don't know and I fear only a lawyer will be able to answer this.
So if you don't mind I would finish a pull request with this 3rd party lib to add KML file support.

**Comment by bobosch** [comment]
I've merged your pull request :-)
