### ISSUE TITLE
Frontend Plugin: Show this marker's popup initially not working

### ISSUE THREAD

**Issue by mccousin** [bobosch/ods_osm#101]
I guess the selected markers info popup for "Show this marker's popup initially" should be opened when visiting the map, right?
This is not working for me.

TYPO3: v11.5.17
ods_osm: v4.0.0

**Comment by albig** [comment]
Yes, this is the intention of this option but didn't work for a while. 

If you have the chance to try the current master, please do so. It should be fixed there. 

A new release 4.1.0 is coming in the next 1-2 days.

**Comment by albig** [comment]
This should not be the case. What kind of errors? Backend/frontend. Do you have a screenshot and/or error message?

**Comment by mccousin** [comment]
In the Backend when clicking on "Extensions" or when saving the Plugin, I get 

Error 503: Class 'HDNET\Calendarize\Domain\Model\Event' not found

**Comment by albig** [comment]
Thank you. Are you using PHP 8.1?

**Comment by albig** [comment]
Ok. Thank you. Can confirm the issue and will look for a fix.

**Comment by albig** [comment]
Please update the master branch and try again. It should not require the calendarize classes anymore.

**Comment by sypets** [comment]
btw, there is an upgrade wizard. If you update from 4.0.0 to master.  I am not sure if this is currently necessary to execute it, but we had some problems a few days ago with the latest master and downgraded again to commit efa197d8d07c99b06d616fdd4f97d8bdd3d119ae for the time being.

I need to find some time to look into it. But it might have been the problem described in this issue. Also the upgrade wizard crashed. Would be happy to test, but not sure when is a good time or if there is still work in progress.

**Comment by albig** [comment]
There is one new upgrade wizard `Bobosch\OdsOsm\Updates\MigrateSettings` which upgrades existing plugin configurations (some flexform settings have changed). This is useful if you have already several plugins on your page and you do not want to reconfigure all.

If you give some more details, I could try to find the bug:

* which PHP-version?
* which TYPO3-version?
* error message of the wizard
* executed via CLI or in backend...

From my part, the master is ready for release.
