### ISSUE TITLE
Exception when running upgrade wizard if pi_flexform is null

### ISSUE THREAD

**Issue by sypets** [bobosch/ods_osm#105]
The following should normally not happen if database is in consistent state. An exception may also be thrown if the pi_flexform field is an empty string. 

I would add a check anyhow, just to be sure and set it to the default values if null or empty (or just skip that record, which would be a quick fix which I think is ok because it is not the job of the upgrade wizard to fix inconsistent data).

I am not sure, why the pi_flexform fields were null. See DB query below where you can see the newest creation date was 2021.  I assume there was a problem unrelated to ods_osm. I checked other tt_content records with ctype='list' and there are only a few, but it does happen.

```
while ($record = $statement->fetch()) {
+           // quick fix for possible value of null in pi_flexform which does not really fix the problem but makes it possible for the wizard to continue
+           if (!($record['pi_flexform'] ?? false)) {
+                  continue;
+           }
            $queryBuilder = $connection->createQueryBuilder();
            $updateResult = $queryBuilder->update('tt_content')
                ->where(
                    $queryBuilder->expr()->eq(
                        'uid',
                        $queryBuilder->createNamedParameter($record['uid'], \PDO::PARAM_INT)
                    )
                )
                ->set('pi_flexform', $this->migrateFlexformSettings($record['pi_flexform']))
                ->execute();
```

Get exception running upgrade wizard:  'Bobosch\OdsOsm\Updates\MigrateSettings'
```
Prerequisite "Database Up-to-Date" fulfilled.

Running Wizard "Migrate settings in EXT:ods_osm plugins"
========================================================


Uncaught TYPO3 Exception Argument 1 passed to Bobosch\OdsOsm\Updates\MigrateSettings::migrateFlexformSettings() 
must be of the type string, null given, called in 
/var/www/mysite/public/typo3conf/ext/ods_osm/Classes/Updates/MigrateSettings.php
on line 105
thrown in file 
/var/www/mysite/public/typo3conf/ext/ods_osm/Classes/Updates/MigrateSettings.php
in line 173

```

**Comment by sypets** [comment]
```
select uid,ctype,list_type,pi_flexform,FROM_UNIXTIME(crdate),FROM_UNIXTIME(tstamp) from tt_content where ctype='list' and list_type like 'ods_osm_pi1' and not deleted and pi_flexform is null;

+--------+-------+-------------+-------------+-----------------------+-----------------------+
| uid    | ctype | list_type   | pi_flexform | FROM_UNIXTIME(crdate) | FROM_UNIXTIME(tstamp) |
+--------+-------+-------------+-------------+-----------------------+-----------------------+
| 300120 | list  | ods_osm_pi1 | NULL        | 2019-07-09 12:00:59   | 2019-07-09 12:00:59   |
| 407795 | list  | ods_osm_pi1 | NULL        | 2021-11-08 09:05:21   | 2021-11-08 09:05:21   |
+--------+-------+-------------+-------------+-----------------------+-----------------------+

```

Setting this to empty string as quick fix will not work - the upgrade wizard will throw another exception. I would recommend to fix the records before running the upgrade wizard but add a check in the upgrade wizard also.

**Comment by sypets** [comment]
After fixing the above problem, I can another error when running the upgrade wizard. This time a generic error message is displayed and the "real" error message is in the log file:

```
Tue, 29 Nov 2022 09:32:21 +0100 [CRITICAL] request="8bbc7c97f0bef" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": 
Core: Exception handler (CLI: BE): Error, code 
#0, file /var/www/mysite/public/typo3conf/ext/ods_osm/Classes/Updates/MigrateSettings.php, 
line 215: 
Call to a member function xpath() on bool- Error:
 Call to a member function xpath() on bool, in file /var/www/mysite/public/typo3conf/ext/ods_osm/Classes/Updates/MigrateSettings.php:215
```


I assume the simplexml_load_string is already failed in checkForOldSettings() and there is not a consistent xml in the field. It might make sense to do sanity checks fix.

Sorry, I realize that this is not really the problem of this extension, but I thinkt this might happen. Especially since I noticed the records with problems are not necessarily very old. 

If you say what the course of action is you would like to take, I might be able to supply a patch.

**Comment by albig** [comment]
Thank you for your investigation. Of course I assumed, that `pi_flexform` contains valid XML. This is not save and I would follow your suggestion to add some sanity checks.

I think, this should be done before each `simplexml_load_string` and already - like you suggested - in `executeUpdate()` but also in `updateNecessary()` (if there is no valid Flexform, we cannot upgrade anything).

Patch is welcome of course. I will look into it this evening.

**Comment by sypets** [comment]
@albig Thank you for answering. I will supply a patch since I have to fix this here anyway to proceed. Do not feel obligated to merge if you want to handle this differently.

I have found another problem: Once I fix the problem with pi_flexform=NULL, I run the Upgrade Wizard again. And if the SQL UPDATE via QueryBuilder returns 0, the Upgrade wizard will abort with false.

This results in a very cryptic error message by TYPO3 core UpgradeWizardRunCommand

`[ERROR] <error>Something went wrong while running Migrate settings in EXT:ods_osm plugins</error>                      `
                                                                                                                      
And there is no log in the error log, so you have to debug to really find  out what is going on.

This probably would not happen if not from the previous problem which results in running upgrade wizard twice where some records are already converted and thus no changes occur on these, but if problem 1 happens you cannot convert the rest of the plugins unless you tweak the code or restore the database. 

So, here it might be better if the UPDATE is only performed if there is a change in the SQL.

code:

```
// this will return 0 if no change is performed on UPDATE (which may happen if wizard is run more than once, which could happen if it crashes previously)
$updateResult = $queryBuilder->update('tt_content')
                ->where(
                    $queryBuilder->expr()->eq(
                        'uid',
                        $queryBuilder->createNamedParameter($record['uid'], \PDO::PARAM_INT)
                    )
                )
                ->set('pi_flexform', $this->migrateFlexformSettings($record['pi_flexform']))
                ->execute();
```

**Comment by albig** [comment]
Thanks for your investigation and the PR. I could reproduce the issue with a huge dump of a ods_osm user. And indeed, there have been few records with `pi_flexform` empty or `NULL`.
