### ISSUE TITLE
No popups anymore when one track-layer is viewed in OpenLayers

### ISSUE THREAD

**Issue by dawnbreak** [bobosch/ods_osm#11]
In the current release of ods_osm I have a problem that popups are not working anymore for tt_address markers as soon as one track-layer is shown. When I de-select the track-layer in the layerselector popups directly work.

Until now I have no idea what the problem is. :-( The last version I used of ods_osm was 1.8.0 and there this problem did not exist.

**Comment by dawnbreak** [comment]
It exchanged the OpenLayers library from 2.13.1 back until 2.10, but all have the same behavior. I don't understand this and it makes no sense.

**Comment by bobosch** [comment]
Strange, it works again if you don't place the track as the last marker in the plugin or if you disable the track layer in the layer switcher...

**Comment by hdi-kw** [comment]
You are right. In the old plugin tracks are displayed first in the layer switcher. In the current version they are at the bottom of the layer switcher always.
