### ISSUE TITLE
"Enable zooming with mouse scroll wheel" in Plugin settings has no effect

### ISSUE THREAD

**Issue by mccousin** [bobosch/ods_osm#110]
Thanks for version 4!

"Enable zooming with mouse scroll wheel" in Plugin settings has no effect in FE.

**Comment by albig** [comment]
Which version of ods_osm do you use?
Which JavaScript library do you use (leaflet / OpenLayers)?

**Comment by mccousin** [comment]
ods_osm: v4.0.0
Leaflet/Mapnik

**Comment by albig** [comment]
If you have the time, try the current master.

**Comment by mccousin** [comment]
now using

ods_osm: dev-master
Leaflet/Mapnik

"Enable zooming with mouse scroll wheel" is turned off, but scrolling is still possible...

**Comment by albig** [comment]
Ok. Thank you for checking the current master. I'll have a look into it.
