### ISSUE TITLE
Type error in displaying card

### ISSUE THREAD

**Issue by linawolf** [bobosch/ods_osm#129]
After an update to TYPO3 v11 / bobosch/ods-osm (v4.1.1)

I get the following error on trying to display the map: 
```
TypeError
Argument 1 passed to TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule() must be of the type array, null given, called in /var/www/html/web/typo3conf/ext/ods_osm/Classes/Controller/PluginController.php on line 153
```

Attached patch solves this for me:

[plugin_controller.patch](https://github.com/bobosch/ods_osm/files/11562046/plugin_controller.patch)

**Comment by albig** [comment]
Thank you for your report and the patch. A little strange, that your extension configuration seems to be unavailable at this point.

I assume, you are using PHP 8.x? Have you tried the current master?

I'll have a look at this later on. A patch-level release 4.1.2 is close anyway.

**Comment by linawolf** [comment]
btw, this happens if you did not yet safe the extension configuration after installation

**Comment by albig** [comment]
> btw, this happens if you did not yet safe the extension configuration after installation

Thank you. This makes sense.
