### ISSUE TITLE
Request: Show geojson polygon-property in vector popup using leaflet

### ISSUE THREAD

**Issue by jthelendmk** [bobosch/ods_osm#137]
We are display postcode-areas using a vetor-element.
We want to show the postcode, which is part of the geojson data, property.postcode, on mouseover.
It would be possible to access this property in typoscript:
`plugin.tx_odsosm_pi1.popup.tx_odsosm_vector.10.value = function (layer) {return String(layer.feature.properties.postcode);}`

But in Bobosch\OdsOsm\Provider\Leaflet.php line 328 this is run through json_encode:
`$jsMarker .= $jsElementVar . '.bindTooltip(' . json_encode($item['popup']) . ");\n";`

Would it be possible to introduce something like `plugin.tx_odsosm_pi1.popup.show_geodataproperty` to add the JS and display the property.
Or have I missed something simpler?

**Comment by albig** [comment]
Thank you for your research and the proposal.

Yes, it should be possible to render the properties of GeoJSON in popups. I missed this feature too, recently.

Could you please attach a sample GeoJSON file? Or raven make a PR?

I'll have a look later this week.

Am 10. Juli 2023 13:16:35 MESZ schrieb jthelendmk ***@***.***>:
>We are display postcode-areas using a vetor-element.
>We want to show the postcode, which is part of the geojson data, property.postcode, on mouseover.
>It would be possible to access this property in typoscript:
>`plugin.tx_odsosm_pi1.popup.tx_odsosm_vector.10.value = function (layer) {return String(layer.feature.properties.postcode);}`
>
>But in Bobosch\OdsOsm\Provider\Leaflet.php line 328 this is run through json_encode:
>`$jsMarker .= $jsElementVar . '.bindTooltip(' . json_encode($item['popup']) . ");\n";`
>
>Would it be possible to introduce something like `plugin.tx_odsosm_pi1.popup.show_geodataproperty` to add the JS and display the property.
>Or have I missed something simpler?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bobosch/ods_osm/issues/137
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- Von /e/ Mail gesendet.

**Comment by jthelendmk** [comment]
That's great to hear. Here is a sample file.

[store2574.zip](https://github.com/bobosch/ods_osm/files/12012531/store2574.zip)

**Comment by albig** [comment]
I'm working (slowly) on a solution to show geoJSON properties in the popup. There is no set of standard properties. You can set color settings like geojson.io does. Or information in custom named properties.

My current approach is to load in the `tx_odsosm_vector` record all available properties. If one doesn't change this, all properties are printed in the popup later. Or you select only the desired properties.

Update in the next days.

**Comment by jthelendmk** [comment]
hi, any news on this issue?

**Comment by albig** [comment]
Thank you for your reminder. I've paused my development in the last two weeks. Hope to finish this next week.

**Comment by jthelendmk** [comment]
Hi, I now had a chance to test your changes. Everything is working great, thank you for your work.
I have two minor issues regarding my use case, using Leaflet.php.

1. If I reset 
plugin.tx_odsosm_pi1.popup.tx_odsosm_vector.10 > 
no PopUp is displayed. I don't really get why. So I cannot remove the title without using css. And the added <br /> on line 327 is hard to remove.
2. Displaying the property name, Leaflet.php line 338, is proplematic, because it is mostly a lower case english word. Again, solvable with CSS, but the colon is still visible.

Any chances, that displaying the headline and the property can be made optional?

Again, thanks for your work

**Comment by albig** [comment]
Thank you for testing the PR #140 

> 1. If I reset
>    plugin.tx_odsosm_pi1.popup.tx_odsosm_vector.10 >
>    no PopUp is displayed. I don't really get why. 

That's a bug, I probably fixed now. I will commit my changes soon.

> So I cannot remove the title without using css. And the added break on line 327 is hard to remove.

The break will only be present, if a title is set.

> 2. Displaying the property name, Leaflet.php line 338, is proplematic, because it is mostly a lower case english word. Again, solvable with CSS, but the colon is still visible.

I've tried to switch to definition list and remove the colon. I think, that's a more proper way. With CSS you can hide the keys. The keys in geojson properties are very different. In your case they are lowercase. But I have examples with uppercase abbreviations. A kind of translation would be great. But at the moment I think, this would make thinks to complex for a rare used feature.

**Comment by jthelendmk** [comment]
Hi, thanks for your feedback.

1. I do not think, that the break is neccessary. If needed, it can be set via TypoScript-wrap.If it is unwanted, there is really no way to cleanly remove it.
2. My only problem here really is the colon. I understand, that translation of the property titles is not feasible, so removing them via CSS is perfectly okay.
Again, thanks for your work
Jan
