### ISSUE TITLE
TYPO3 12 compatibility

### ISSUE THREAD

**Issue by matthaa** [bobosch/ods_osm#145]
Hi,
great extension, thanks al lot!
Is there any roadmap for a version that is compatible with TYPO3 12?
Thanks for a hint,
Matthias

**Comment by albig** [comment]
Dear Matthias,

please have look at the current master. This will be released as 4.2.0 soon and is compatible with TYPO3 12.4.

Looking for your feedback.

Alexander

Am 6. Oktober 2023 10:07:33 MESZ schrieb Matthias Haack ***@***.***>:

**Comment by matthaa** [comment]
Hi Alexander,
good news, thanks.
Matthias
