### ISSUE TITLE
Missing layers

### ISSUE THREAD

**Issue by dheckl** [bobosch/ods_osm#156]
After upgrading to TYPO3 version 12.4, we've encountered a problem where all the layers have disappeared. As a result, the map displayed in the frontend is showing up as grey. We've refreshed the static database content, yet this has not resolved the problem. Any idea what's wrong?

![Bildschirmfoto 2024-01-22 um 20 07 24](https://github.com/bobosch/ods_osm/assets/9950090/03a887e3-be53-4097-ba9a-e837ddfc9e14)

**Comment by albig** [comment]
Did you run all upgrade wizards? Especially `EXT:ods_osm: Migrate plugin flexform settings`?

What do you see as layer records on uid = 0? Should look like this:

![2024-01-22_20-18](https://github.com/bobosch/ods_osm/assets/3354500/71c4d357-2d35-4d64-825c-0069b75083da)

**Comment by dheckl** [comment]
Running `./vendor/bin/typo3 upgrade:run`, I get following result:

```
! [NOTE] Wizard odsOsmFileLocationUpdater does not need to make changes. Marking wizard as done.                       
! [NOTE] Wizard odsOsmMigrateSettings does not need to make changes. Marking wizard as done.
```

I tried to run the SQL queries in `ext_tables_static+adt.sql` manually and received the error "Column count doesn't match value count at row 1". As all tables were empty, I deleted them and re-run upgrade wizard + refreshed static db content. Now it works again. Looks to me that upgrade wizard does not update the scheme with the changes introduced with 918a6b7.

**Comment by albig** [comment]
Have you run a db compare before? The upgrade wizard won't do the scheme upgrades.

Finally, it works again for you?

**Comment by dheckl** [comment]
I ran the Analyze Database Structure job before, but didn't spot anything related to ods_osm. However, it's working now, so we can consider the issue resolved. Thanks for your help!

**Comment by albig** [comment]
Thank you for your feedback.
