### ISSUE TITLE
 custom marker icon

### ISSUE THREAD

**Issue by Hobokens** [bobosch/ods_osm#157]
I would like to use a custom marker icon in the extension ods_osm for TYPO3 12 - so far without success. For this I have

1. created my own marker with the extension;
2. added this marker to a category;
3. assigned the category to a tt_address entry.

Unfortunately, I still see the default marker of ods_osm .  (`ods_osm/Resources/Public/Icons/marker-icon.png`)

**Comment by albig** [comment]
Do you use Leaflet or OpenLayers? Both should work.

Your steps are ok. What data records did you select in the plugin settings for "Records to show"? You must select the `sys_category` records, not the `tt_address` records itself. With only `tt_address` there is an open issue #79.

Here you find a working example:

https://osm.bigga.de/examples/leaflet/marker

**Comment by Hobokens** [comment]
Thanks for your quick answer. After choosing the category instead of the tt_address record the custom icon is shown.

**Comment by Hobokens** [comment]
Thanks for your quick answer. After choosing the category instead of the tt_address record the custom icon is shown.
