### ISSUE TITLE
TYPO3 12.4.10 problem

### ISSUE THREAD

**Issue by kaystrobach** [bobosch/ods_osm#158]
<blockquote type="cite" style="font-family: Helvetica; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><div><center style="caret-color: rgb(0, 0, 0); font-family: Helvetica; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 246, 246); text-decoration: none; width: 832px;"><div class="email-container" style="max-width: 680px; margin: 0px auto;">
Fatal error: Bobosch\OdsOsm\Updates\FileLocationUpdater and Psr\Log\LoggerAwareTrait define the same property ($logger) in the composition of Bobosch\OdsOsm\Updates\FileLocationUpdater. However, the definition differs and is considered incompatible. Class was composed in /html/typo3/typo3conf/ext/ods_osm/Classes/Updates/FileLocationUpdater.php | Fatal error: Bobosch\OdsOsm\Updates\FileLocationUpdater and Psr\Log\LoggerAwareTrait define the same property ($logger) in the composition of Bobosch\OdsOsm\Updates\FileLocationUpdater. However, the definition differs and is considered incompatible. Class was composed in /html/typo3/typo3conf/ext/ods_osm/Classes/Updates/FileLocationUpdater.php
-- | --
Fatal error: Bobosch\OdsOsm\Updates\FileLocationUpdater and Psr\Log\LoggerAwareTrait define the same property ($logger) in the composition of Bobosch\OdsOsm\Updates\FileLocationUpdater. However, the definition differs and is considered incompatible. Class was composed in /html/typo3/typo3conf/ext/ods_osm/Classes/Updates/FileLocationUpdater.php

</div></center></div></blockquote>

This prevents the update to 12.4.10. Maybe we can provide a patch in the future, but would be happy if there would be a general solution.

Thank you.

**Comment by albig** [comment]
Thank you for reporting.

You do an TYPO3 ugprade from 11.5 to 12.4 with ods_osm installed before?

**Comment by kaystrobach** [comment]
> Thank you for reporting.
> 
> You do an TYPO3 ugprade from 11.5 to 12.4 with ods_osm installed before?

no 12.4.9 to 12.4.10

**Comment by kaystrobach** [comment]
release is done, we are trying it.
