### ISSUE TITLE
Repository not in sync with TER

### ISSUE THREAD

**Issue by fladi** [bobosch/ods_osm#17]
This seems to be the official repository for ods_osm but does not have the latest version (1.11.6) available. Maybe this is just a simple case of a missing push.

Also it would be nice to have release tags for each release.

**Comment by bobosch** [comment]
Yes, I've forgotten to commit the version update. Further I've skipped one :-(
I'm new to github ... I've created a release tag - hope this is correct :-)

**Comment by labneu** [comment]
Hey Robert,

 

i would like to disable the Start and end icon in cycle Tracks / leaftlet

 

could you tell me how

 

best Regards and happy new yeard 

 

Jean Louis Leclerc



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
