### ISSUE TITLE
tracks - geoPHP error on save

### ISSUE THREAD

**Issue by mysailing** [bobosch/ods_osm#170]
when saving a track I get 
(1/1) Error
Class 'geoPHP\geoPHP' not found

**Comment by mysailing** [comment]
this is the case since I migrated from 4.1.3 to 4.2.1

**Comment by albig** [comment]
What's your TYPO3 version and how did you install `ods_osm`? Via TER or via composer?

**Comment by mysailing** [comment]
Typo3 11.5.36 and the install was done via the extension manager

**Comment by albig** [comment]
OK, thank you. That's the problem. The geoPHP version shipped with ods_osm 4.1 was not compatible with PHP 8.2. The current used fork in version 4.2 is installed if using composer, which is the default today,  I think. But it's not inside the TER package.

I see two solutions / workarounds:

1. catch the exception and do not calculate the bounding box.
2. copy the geoPHP fork into ods_osm
3. do nothing ;-)

Am 27. März 2024 20:32:25 MEZ schrieb mysailing ***@***.***>:
>Typo3 11.5.36 and the install was done via the extension manager
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bobosch/ods_osm/issues/170#issuecomment-2023810015
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- Von /e/OS E-Mail gesendet.

**Comment by mysailing** [comment]
Thx for the feedback ...

unfortunately without bounding box, the starting view of the map will not focus on the right area. I see with my hoster on how the composer install can be facilitated - at current I lack rights to do so.

**Comment by mysailing** [comment]
appreciated - enjoy Easter.

**Comment by simonschaufi** [comment]
> I'll have a look after Easter into option 2.

You can have a look at what the Solr extension is doing. They also load composer packages into their extension.

**Comment by albig** [comment]
Thank you for this hint. I'll have a look.

Am 28. März 2024 12:08:31 MEZ schrieb Simon Schaufelberger ***@***.***>:
>> I'll have a look after Easter into option 2.
>
>You can have a look at what the Solr extension is doing. They also load composer packages into their extension.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bobosch/ods_osm/issues/170#issuecomment-2024928488
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- Von /e/OS E-Mail gesendet.
