### ISSUE TITLE
Entire address is written into field "address" on save

### ISSUE THREAD

**Issue by sypets** [bobosch/ods_osm#180]
When saving an existing address entry which only contains the street in the field "address" and also has other fields country, zip, city etc. filled out, the field `address` is filled with redundant data.

The behaviour described below happens only if ods_osm is installed, not if only tt_address is used.

According to the tt_address documentation it seems to be correct that address contains only the street: https://docs.typo3.org/p/friendsoftypo3/tt-address/8.0/en-us/Introduction/Index.html

![image](https://github.com/bobosch/ods_osm/assets/13206455/ad7f0e99-7251-47a4-a205-c1191b053423)

## Reproduce

Adress is entered:

```
address: Bremer Straße 7
city: Vechta
zip: 49377
region: Niedersachsen
country: Deutschland

```
![image](https://github.com/bobosch/ods_osm/assets/13206455/5d92fc87-dba4-4004-b60d-472c01736c8b)

If I enter it this way in a system with only tt_address and save,  the field "address" stays the same: "Bremer Straße 7".

But if I enter it in a system with ods_osm, this happens:

![image](https://github.com/bobosch/ods_osm/assets/13206455/9a70aeed-305c-4cbc-8781-bbed11fcb121)

address now contains: "Bremer Straße 7, 49377 Vechta, Deutschland" and we have redundant data, which also results in redundant data in the Frontend:

![image](https://github.com/bobosch/ods_osm/assets/13206455/23878496-c59a-4f28-82e2-cd66b4a14822)

## Versions

- ods_osm: master
- tt_address: 7.1.0
- PHP 8.2
- TYPO3 11.5.36

**Comment by albig** [comment]
Thank you for the detailed bug report. It's indeed a bug. I'll provide a fix today.

**Comment by sypets** [comment]
> Thank you for the detailed bug report. It's indeed a bug. I'll provide a fix today.

Awesome, thanks. :+1:  I'll check it out on Monday.
