### ISSUE TITLE
An exception occurred while saving the data: PHP Warning: Undefined array key "region" 

### ISSUE THREAD

**Issue by Pekkonen** [bobosch/ods_osm#197]
Hi!
I have a bug with ods_osm, but I'm not sure in 100% in that.
I have TYPO3 12.4.21, bobosch/ods-osm - 4.2.2 and cobweb/external_importb - 7.2.5.
Then I trying to import CSV file to tt_address table I have an exception about ods_osm:

An exception occurred while saving the data: PHP Warning: Undefined array key "region" in /var/www/html/site/vendor/bobosch/ods-osm/Classes/TceMain.php line 318 (code: 1476107295, location: /var/www/html/site/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php at line 141)

In MySQL tt_address I have a correct structure with region table. 
TYPO3 database analyse I have - "Database schema is up to date. Good job!"

When I uninstall ods_osm everything is going right without any errors.
In import process I have just mapping data from CSV columns to the tt_address columns, but no handling "region" column

**Comment by albig** [comment]
Thank you for the report. I'll have a look this evening.

**Comment by Pekkonen** [comment]
When I'm trying to use custom  transformation for latitude and longitude (not simple get/put values from CSV, but transform it in my viewhelper) I have a same error bu about longitude:
An exception occurred while saving the data: PHP Warning: Undefined array key "longitude" in /var/www/html/site/vendor/bobosch/ods-osm/Classes/TceMain.php line 318 (code: 1476107295, location: /var/www/html/site/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php at line 141)

**Comment by albig** [comment]
Don't know, howto reproduce. Could you please share a line of your CSV file and/or the ViewHelper your are using?

**Comment by Pekkonen** [comment]
[B2_Unterversorgte_Privatadressen.csv](https://github.com/user-attachments/files/17376995/B2_Unterversorgte_Privatadressen.csv)
Content of TCA file for this import:
```
<?php

$GLOBALS['TCA']['tt_address']['ctrl']['external'] = [
	0 => [
		'connector' => 'csv',
		'parameters' => [
			'filename' => 'fileadmin/import/weisse_flecken/B2_Unterversorgte_Privatadressen.csv',
			'encoding' => 'utf8',
			'delimiter' => ",",
			'skip_rows' => 1
		],
		'referenceUid' => 'last_name',
		'data' => 'array',
		'pid' => 1221,
		'enforcePid' => true
	]
];

$GLOBALS['TCA']['tt_address']['columns']['zip']['external'][0] = [
	'field' => 'PLZ'
];

$GLOBALS['TCA']['tt_address']['columns']['name']['external'][0] = [
	'field' => 'Strasse'
];

$GLOBALS['TCA']['tt_address']['columns']['last_name']['external'][0] = [
	'field' => 'FID'
];

$GLOBALS['TCA']['tt_address']['columns']['city']['external'][0] = [
	'field' => 'Ort'
];

$GLOBALS['TCA']['tt_address']['columns']['address']['external'][0] = [
	'field' => 'Strasse'
];

$GLOBALS['TCA']['tt_address']['columns']['building']['external'][0] = [
	'field' => 'Hausnummer'
];

$GLOBALS['TCA']['tt_address']['columns']['room']['external'][0] = [
	'field' => 'Zusatz'
];

$GLOBALS['TCA']['tt_address']['columns']['longitude']['external'][0] = [
    'field' => 'Y_Koord'
];
$GLOBALS['TCA']['tt_address']['columns']['latitude']['external'][0] = [
    'field' => 'X_Koord'
];
```
This returned an error:
An exception occurred while saving the data: PHP Warning: Undefined array key "region" in /var/www/html/site/vendor/bobosch/ods-osm/Classes/TceMain.php line 318 (code: 1476107295, location: /var/www/html/site/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php at line 141)

**Comment by Pekkonen** [comment]
Hey!
This is my environment:
TYPO3 Version - 12.4.21
nginx -1.18.0
PHP - 8.2.5
tt_address same - 9.0.1.

> The exception complains about the missing region which is a tt_address field in your data. Maybe you could just add it to the TCA-configuration as dummy? Same should happen with the country field.
You're quite right!
When I added these two fields to TCA - `region` and `country ` I have a sucessfull import without any errors!
I'll check how I could change a code for this, maybe add new columns in CSV...
Thanks for your support!

**Comment by albig** [comment]
Thank you for your feedback. It's not the PHP version but you run TYPO3 in Debug-Mode. That's why the "PHP warning" leads into an exception.

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/ErrorAndExceptionHandling/Examples/Index.html#debugging-and-development-setup

So you have multiple ways to work around this warning (disable debug-mode, add the missing fields, disable address lookup...). 

And I will fix `ods_osm` to avoid this warning in a future release.
