### ISSUE TITLE
Not possible to center a map via TS

### ISSUE THREAD

**Issue by anrainer** [bobosch/ods_osm#20]
Hi Robert,

first of all, thank you so much for your wonderful Typo3 extension ods_osm and for sharing it with the community!

By making first experiments in using ods_osm maybe I discovered a little bug.

When I insert a content element (Plugin/OpenStreetMap) an a page and I tr to use TS in an Ext Template on the same page it seems impossible to define the center of the map via

plugin.tx_odsosm_pi1 {
  marker {
    tt_address_group = 4711
  }
  zoom = 13
  lon = 10.0
  lat = 50.0
}

This is because the empty fields of the Flexform appear as $flex["lon"] = 0.000  and $flex["lat"] = 0.000 in the array $flex and so the condition in line 308 of class.tx_odsosm_pi1.php always holds.

A working patch for me would be to put in before line 93:

    if($flex["lat"] == 0.0 and $flex["lon"] == 0.0) {
      unset($flex["lat"]);
      unset($flex["lon"]);
    }

This is not a clean and respectable fix though, and because I have zero knowledge in Typo3 extension development I wanted to ask if you could fix that and update the TER?

Best regards and greetings from Franconia

Andreas Rainer

**Comment by bobosch** [comment]
Hi Andreas,

yes, this is a bug. The `if($value)` in line 79 should prevent storing empty values in $flex. No Idea if this has worked with an older php version.
Please try commit 50b0c0ec9661c91d0b4f5a94e3eda02d7d13f245 - $flex shouldn't be set... (Feedback welcome

**Comment by bobosch** [comment]
Thanks for figure this out.
