### ISSUE TITLE
[1.12.0] Coordinatepicker Wizard in 6.2

### ISSUE THREAD

**Issue by dawnbreak** [bobosch/ods_osm#21]
In TYPO3 6.2 I get following error when I click on the search coordinate button:
> Uncaught TYPO3 Exception
> #1294585070: No module "wizard_coordinatepicker" could be found. (More information)
> UnexpectedValueException thrown in file
> /srv/.../typo3_62/typo3/mod.php in line 46.

In 7.6 there is no such problem.

**Comment by bobosch** [comment]
Please check commit f07143428387f7095e88b36b59ead03c78cb0e01

**Comment by dawnbreak** [comment]
That error is gone, but another one appears:

> exec_SELECTquery
> caller	TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery
> ERROR	Unknown column 'tx_odsosm_lat' in 'field list'
> lastBuiltQuery	SELECT tx_odsosm_lat AS lat,tx_odsosm_lon AS lon FROM tt_address WHERE uid=2
> debug_backtrace	require(typo3conf/ext/ods_osm/wizard/index.php),typo3_62/typo3/mod.php#32 // tx_odsosm_wizard->main#122 // tx_odsosm_wizard->moduleContent#32 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_SELECTquery#69 // TYPO3\CMS\Core\Database\DatabaseConnection->debug#305
> Uncaught TYPO3 Exception
> 1: PHP Warning: Illegal string offset 'mode' in /srv/.../typo3conf/ext/ods_osm/wizard/index.php line 97

**Comment by bobosch** [comment]
Sorry, forgotten one line to change .. I've amended the las commit

**Comment by dawnbreak** [comment]
Two more unfortunately :-(

> TYPO3\CMS\Core\Error\ErrorHandler::handleError(2, "Illegal string offset 'mode'", "/srv/.../typo3conf/ext/ods_osm/wizard/index.php", 97, array)
> /srv/.../typo3conf/ext/ods_osm/wizard/index.php:
> 00097: '.$library->getMapBE($layers,$this->P['params']['mode'],$row['lat'],$row['lon'],$row['zoom'],$this->doc).'

And the other is when I edit the lon/lat of the osm plugin (tt_content uid=3). lon/lat are in the Flexform of the CE.
> exec_SELECTquery
> caller	TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery
> ERROR	Unknown column 'lon' in 'field list'
> lastBuiltQuery	SELECT lon AS lon, lat AS lat FROM tt_content WHERE uid=3
> debug_backtrace	require(typo3conf/ext/ods_osm/wizard/index.php),typo3_62/typo3/mod.php#32 // tx_odsosm_wizard->main#122 // tx_odsosm_wizard->moduleContent#32 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_SELECTquery#69 // TYPO3\CMS\Core\Database\DatabaseConnection->debug#305
