### ISSUE TITLE
[1.12.0] Missing coordinates in Openlayers mapMarkers

### ISSUE THREAD

**Issue by dawnbreak** [bobosch/ods_osm#22]
In class.tx_odsosm_openlayers.php#L124 it seems like lat and lon are missing.

**Comment by bobosch** [comment]
Hi! Have you used the update script? Field names in tt_address have changed...

**Comment by dawnbreak** [comment]
Yes I run the update script. Then I deleted the old columns with the compare database and when I edit the address I also see the coordinates. But in the mapMarker they are empty.

**Comment by ToelkeStwm** [comment]
the sys_category relations are somehow inverted compared to the old tt_address_group settings.
With this change in class.tx_odsosdm_pi1.php Line 216

from

$res=$GLOBALS['TYPO3_DB']->exec_SELECT_mm_query('tt_address.*', 'tt_address', 'sys_category', 'sys_category_record_mm', 'AND sys_category.uid=' . $item . tx_odsosm_div::getWhere('tt_address',$this->cObj));
						
to
							$res=$GLOBALS['TYPO3_DB']->exec_SELECT_mm_query('tt_address.*', 'sys_category', 'sys_category_record_mm', 'tt_address', 'AND sys_category.uid=' . $item . tx_odsosm_div::getWhere('tt_address',$this->cObj));

it works here.

**Comment by ToelkeStwm** [comment]
sorry wrong issue.... but this is also one. :/

**Comment by bobosch** [comment]
@dawnbreak Does this issue still exists in version 1.12.2 ?
@ToelkeStwm Thanks! Please post the next time 30 minutes earlier - I had it just fixed as your message arrived ;-)

**Comment by dawnbreak** [comment]
The coordinates are there now, but I need a new clean system. Getting several other errors in the javascript console and no map output anymore.
