### ISSUE TITLE
JSeventFuncCalls deprecated

### ISSUE THREAD

**Issue by hdi-kw** [bobosch/ods_osm#23]
In TYPO3 7.6 no map is displayed and I get "ReferenceError: T3_onloadWrapper is not defined". In typo3conf/ext/ods_osm/pi1/class.tx_odsosm_pi1.php there is: $GLOBALS['TSFE']->JSeventFuncCalls['onload'][] = "create_".$this->config['id']."();";
This seems to be deprecated:
typo3/sysext/core/Documentation/Changelog/7.0/Deprecation-62363-TSFE-JSfuncCalls.rst "Deprecation: #62363 - TSFE->JSeventFuncCalls disabled"

**Comment by bobosch** [comment]
Please try commit 3cbfdf905caf12da4b5446508681457e75ea80c0

**Comment by hdi-kw** [comment]
perfect. Thanks!
