### ISSUE TITLE
floatval is locale aware and breaks extension e.g. in german

### ISSUE THREAD

**Issue by ToelkeStwm** [bobosch/ods_osm#24]
Hi, there is an issue with the generation of the longitude and latitude. Just want to point it out, no fix at the moment.

The problem is, that floatval generates a locale aware number presentation. This means that
here

return "mapCenter(".$this->config['id'].",".floatval($lat).",".floatval($lon).",".intval($zoom).");";

generates something like
in German:         mapCenter(osm_13431,48,1,11,558,12);  <= floatvalue with ","
in US English:     mapCenter(osm_13431,48.1,11.558,12);  <= floatvalue with "."

should be the same for center position and markers. 

I just noticed this.

**Comment by bobosch** [comment]
Wow. floatval is used since the creation of the extension, and nobody noticed this - it seems that most TYPO3 installations are running with the default locale... Thanks for the hint!

**Comment by bobosch** [comment]
Please check out commit f725fd043db146942891420a273c0c24fa5164cb
I'm replaced all parameters with json_encode

**Comment by ToelkeStwm** [comment]
:)) Thank you! Yes it is working :))
