### ISSUE TITLE
MapQuest requires API Key since 11.July 2016

### ISSUE THREAD

**Issue by nicotillmann** [bobosch/ods_osm#25]
Dear Robert ,
starting 11 July  MapQuest requires an API Key, does ods_osm alreday is prepared to handle this requirement ?

So far I didn't found a solution for the problem which looks like this:
http://otile2.mqcdn.com/tiles/1.0.0/osm/1/1/0.png

Thanks a lot for the extension in generell and your support in particular

Nico Tillmann

**Comment by bobosch** [comment]
Hi,

It works only with a special plugin :-(

"MapQuest provides a plugin for Leaflet, but not any tools for OpenLayers. Direct access to map tiles is not allowed
outside the MapQuest sdks."

Regards, Robert

Am 25.07.2016 um 19:00 schrieb nicotillmann:

**Comment by albig** [comment]
Won't fix.
