### ISSUE TITLE
add min_zoom option for leaflet

### ISSUE THREAD

**Issue by hannesbochmann** [bobosch/ods_osm#26]
Is it possible to add the min_zoom option for the leaflet library? Should not be more than adding the field in the sql/TCA and add the following to tx_odsosm_leaflet after line 52:
`if($layer['min_zoom']) $options['minZoom']=$layer['min_zoom'];`

If you like I can also provide a pull request.

**Comment by hannesbochmann** [comment]
Ping.

**Comment by darthnorman** [comment]
Would love to see that feature.

**Comment by bobosch** [comment]
Sorry, not much time ...
Comitted :-)

**Comment by hannesbochmann** [comment]
Perfect, thank you!
