### ISSUE TITLE
PHP Warning in tx_odsosm_leaflet

### ISSUE THREAD

**Issue by hannesbochmann** [bobosch/ods_osm#28]
In line 153 $this->layers[1] needs to be an array but is sometimes null. A simple array cast should do the trick.
(array) $this->layers[1]

**Comment by bobosch** [comment]
I tried to reproduce this case, but I don't get it. In which case this happens?

**Comment by hannesbochmann** [comment]
TYPO3 6.2.30
PHP: 5.5.9
ods_osm: 2.1.0
ods_osm_tt_address: 3.0.2

I added a ods_osm Plugin with the following configuration:

- using sys_category as source of datasets -> tt_address entries are linked to this sys_category
- leaflet as engine
- main layer is a custom one (do you need all the data of the layer?)
- show popups per click
- zoom: 9

**Comment by bobosch** [comment]
I see, an uninitialized array.
Could you please exchange line 3 into
	protected $layers = array(0 => array(), 1 => array());
if this work for you? I will include this in the next version.

**Comment by hannesbochmann** [comment]
It works.

**Comment by labneu** [comment]
Typo3 vers. 7.6.15
ods_osm 2.1.0
hi robert,
i have 2 problem 
When I activate the program "leaflet" I get  error message : Oops, an error occurred! Code: 2017011613143902ef42eb . (screenshot1)
I have changed / added in the file "ext_typoscript_setup.txt" to create a link of the popup. It has first worked but then when activating the link I get the error message 404. Do you have a better solution? (screenshot2)
popup {
    	 	 fe_users = COA
     		 fe_users {
      	10 = TEXT
        10.field = title
        10.wrap = <b>|</b><br />

        20 = TEXT
        20.field = company
        20.wrap = <b>|</b><br />

        30 = TEXT
        30.field = zip
        30.wrap = <b>|</b>&nbsp;

        40 = TEXT
        40.field = city
        40.wrap = <b>|</b>&nbsp;

        50 = TEXT
        50.field = middle_name
        50.wrap = <br /><a href="index.php?id=|">More-Info</a>&nbsp;
        50.required = 1 

			}
![ods_osm1](https://cloud.githubusercontent.com/assets/8362890/21982977/2071c040-dbef-11e6-9949-740ab6c9f5ec.jpg)
![ods_osm2](https://cloud.githubusercontent.com/assets/8362890/21982976/20717856-dbef-11e6-82f3-5fbad7ea0862.jpg)

**Comment by bobosch** [comment]
labneu: look at issue https://github.com/bobosch/ods_osm/issues/29

**Comment by bobosch** [comment]
Thanks for your feedback!
