### ISSUE TITLE
Display image from tt_address record

### ISSUE THREAD

**Issue by michelrossier** [bobosch/ods_osm#32]
Do you provide a way to display an image that has been defined in a tt_address record? TYPO3 8.7.1, latest ods_osm, ods_osm_tt_address and tt_address are in use.

**Comment by bobosch** [comment]
This works in the past - until tt_address switched to FAL
https://github.com/FriendsOfTYPO3/tt_address/issues/12
The popup window is fully configurable with Typoscript.
If you find a way to use the image in the FAL storage, please let me know.

**Comment by lorenzulrich** [comment]
To solve this problem, https://github.com/FriendsOfTYPO3/tt_address/blob/v3.2.2/pi1/class.tx_ttaddress_pi1.php#L393 needs to be changed from `file:current:uid` to `file:current:originalUid`. I don't know if that's the correct solution but I guess so.

**Comment by bobosch** [comment]
I've found another way

```
plugin.tx_odsosm_pi1 {
  popup {
    tt_address {
      30 = IMAGE
      30.file.import = fileadmin/user_upload/
      30.file.import.override.field = image
    }
  }
}
```

Feedback is welcome - I will include this example in the documentation.

**Comment by mvolland** [comment]
For me it does't work (TYPO3 7.6.29/8.7.16 and tt_address 3.2.4)

I get the image tag, but with wrong source:
`<img src="/typo3/sysext/extensionmanager/Resources/Public/Images/Distribution.png" alt="" width="300" height="225">`

**Comment by albig** [comment]
With FAL on TYPO3 10.4 and 11.5 the TypoScript is a little longer. 

This way, you can get the image from `fe_users` and `tt_address` records. This will be part of the default TypoScript in upcoming release.

```
plugin.tx_odsosm_pi1 {
  popup {
    tt_address = COA
    tt_address {
      9 = FILES
      9 {
        references {
          table = tt_address
          fieldName = image
        }
        renderObj = IMAGE
        renderObj {
          file {
            import.data = file:current:uid
            treatIdAsReference = 1
            width = 150c
            height = 150c
          }
          altText.data = file:current:alternative
          titleText.data = file:current:title
          stdWrap.typolink.parameter.data = file:current:link
        }
      }
      10 = TEXT
      10.field = name
      10.wrap = <h2>|</h2>
      20 = TEXT
      20.field = description
      20.htmlSpecialChars = 0
    }
  }
}

```
