### ISSUE TITLE
Not more possible to add a track file

### ISSUE THREAD

**Issue by claude27** [bobosch/ods_osm#42]
When adding a gpx or a kml file as track, the following error is shown:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'Bobosch\OdsOsm\geoPHP' not found | Error thrown in file /var/www/html/public/typo3conf/ext/ods_osm/Classes/TceMain.php in line 23. 
(ods_osm master version, installed via composer, in TYPO3 9.5.13, PHP 7.2)

Solution: It seems to me that setting 
use geoPHP;
in line 4 of TceMain.php solves the problem?

**Comment by albig** [comment]
Thank you for your bug report. I've just noticed this too.

**Comment by albig** [comment]
@claude27 could you please try the branch fix-42-include-geophp? This fetches the geoPHP class via composer requirement. Maybe you need to make a composer update. In my testcase it is working.

**Comment by claude27** [comment]
@albig thank you! I tried it and it worked perfectly!

**Comment by albig** [comment]
Closed by #44.
