### ISSUE TITLE
Its not possible to disable mousewheelscroll

### ISSUE THREAD

**Issue by Jaiprucl** [bobosch/ods_osm#53]
I am trying do disable the mousewheelscroll function, but there is no option in the configuration for the Leaflet Map. 
This dirty code in the Leaflet.php works for me:

`$jsMain =
            $this->config['id'] . "=new L.Map('" . $this->config['id'] . "', {scrollWheelZoom: false, tap: false});`

but probably until the next update or is there another option i havn't see?

**Comment by albig** [comment]
We should make this configurable via flexform as it is done for `mouse_navigation` of openlayers is done.

What means `tab:false`? It his another option?
