### ISSUE TITLE
radial search

### ISSUE THREAD

**Issue by heikohaensge** [bobosch/ods_osm#57]
Are there plans to implement a radial search which is working with fe_users entries?
Something like the extension https://extensions.typo3.org/extension/ods_osm_search/
approached?

**Comment by heikohaensge** [comment]
No response in 6 months? Is this project still active?
If not, are there any recommendations for other map extensions?

**Comment by albig** [comment]
Please have a look at the releases: https://github.com/bobosch/ods_osm/releases

Obviously there are no plans currently. You're welcome to contribute.

**Comment by heikohaensge** [comment]
I'm open to contribute i.e. in testing. 
But I can't do the programming.
