### ISSUE TITLE
Add action to marker when clicked?

### ISSUE THREAD

**Issue by TomQv** [bobosch/ods_osm#77]
I want to link markers with pages of my website. 
Currently markers are created as users and I only can set the Name which will appear in the info-box of the marker.
But now I would like the user go to another page of the site, if he clicks on the marker.

Is this somehow possible?

**Comment by albig** [comment]
I don't think so. The implementation uses Leaflet's `bindPopup()` method.

You can change the content of the Popup (info-box) by TypoScript. Have a look at `plugin.tx_odsosm_pi1.popup`. So you could add an hyperlink into the opended box.

Just clicking the marker and following a link is not implemented.

**Comment by TomQv** [comment]
Sorry, I'm not so familiar with Typo3 yet, where do I find this plugin?
