### ISSUE TITLE
Question - Limit the maximum zoom level

### ISSUE THREAD

**Issue by TomQv** [bobosch/ods_osm#78]
Is there a way to limit the maximum zoom level the user can zoom in with Leaflet?
I dont want users to zoom in more then level 12.

**Comment by albig** [comment]
This is possible but has to be done in the layer record (on pid = 0). There you can set e.g. for Mapnik the `min_zoom` and `max_zoom`.

**Comment by TomQv** [comment]
Thanks, found it and its working.
