### ISSUE TITLE
Question: how to add baselayer plus overlay?

### ISSUE THREAD

**Issue by TomQv** [bobosch/ods_osm#80]
Hi, I added baselayer "Stamen Watercolor" and I also want the overlay "Stamen Terrain Labels".
So far I only can show the overlay with then layerswitcher, but I don't want the layerswitcher in the map.
Is there a way to have overlay "Stamen Terrain Labels" always activated ?

**Comment by albig** [comment]
No, this is currently not working. There we have to look at the Leaflet documentation and add a new feature, to add all (or flexform-selected?) layers to the map.

This could be a good starting point: https://leafletjs.com/examples/layers-control/

**Comment by albig** [comment]
This should work in upcoming release 4.1.0.

**Comment by albig** [comment]
Fixed with release [4.1.0](https://github.com/bobosch/ods_osm/releases/tag/v4.1.0)
