### ISSUE TITLE
Error if you use multiple fe_user groups

### ISSUE THREAD

**Issue by MichiSpandl** [bobosch/ods_osm#81]
In PluginController.php - from Line 318 - it should be `$records[$t][$resArray['uid']] = $resArray; `and not `$records[$t][$r['uid']] = $resArray;` because there is no $r and then the array contains only one entry! So replace $r with $resArray :)

**Comment by albig** [comment]
Thank you for reporting. Is this the same issue like #79? In #79 I suppose, we talk about different things or I had a first different understanding. With the last comment in #79 and your bug report it looks for related. But I didn't try it yet.

Do you have the capabilities to make a tiny pull request with your changes described above?
