### ISSUE TITLE
Broken Icon URL

### ISSUE THREAD

**Issue by ut** [bobosch/ods_osm#88]
In the Leaflet section it seems that an icon URL returns (at my installation) an incorrect URL.
This icon is used in the control layers

![image](https://user-images.githubusercontent.com/159547/177975541-5cb0f9a7-7a03-4ecd-ae11-1364d00c857c.png)

In the source code the icon URL is shown with the double path part "Core"

![image](https://user-images.githubusercontent.com/159547/177975621-514963fd-d1bd-4993-b0ea-226279681133.png)

The parts where this URL is build are in Classes/Provider/Leaflet.php

Line 31
https://github.com/bobosch/ods_osm/blob/abad6f4b0f7097170ac732932b8d903cd9c031fa/Classes/Provider/Leaflet.php#L31

and then in line 269

https://github.com/bobosch/ods_osm/blob/abad6f4b0f7097170ac732932b8d903cd9c031fa/Classes/Provider/Leaflet.php#L269

Extension version is  4.0.0 in a Typo3 v10 installation.

If someone can confirm this issue I'd be happy to make a PR.

Besides, thanks @bobosch and contributors for this awesome extension!

**Comment by albig** [comment]
Thank you for reporting. This is good analyzed and I pretty sure, the path component `Core/` is pretty stupid in line 269.

https://github.com/bobosch/ods_osm/blob/abad6f4b0f7097170ac732932b8d903cd9c031fa/Classes/Provider/Leaflet.php#L269

Your're welcome to provide a pull request!
