### ISSUE TITLE
Can you release another version please?

### ISSUE THREAD

**Issue by sypets** [bobosch/ods_osm#99]
Latest release is 4.0.0 (from May, 2022):. https://github.com/bobosch/ods_osm/tags

Since then, several changes (and bugfixes) were merged.

* TER: https://extensions.typo3.org/extension/ods_osm
* packagist: https://packagist.org/packages/bobosch/ods-osm

**Comment by albig** [comment]
@sypets and all: Please have a short look at the current master. I merged my changes of the last weeks, cleaned up the code a bit with typo3-rector and fixed some hidden and broken features.

Depending on your feedback, I would make a tiny update to the documentation and a release in the next 1-2 days.

**Comment by albig** [comment]
Done with release [4.1.0](https://github.com/bobosch/ods_osm/releases/tag/v4.1.0)
